parameters:
solution: '**/*.sln'
buildPlatform: 'Any CPU'  
buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs: 
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: DotNetCoreCLI@2
 # displayName: 'Build the project - ${{ parameters.buildConfiguration }}'
#  inputs:
  #  command: 'build'
   # arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    #projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'
    zipAfterPublish: true